[package]
name = "ntimes"
version = "0.1.0"
authors = ["Scott Newcomer <snewcomer24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"
structopt = "0.3"

